### ISSUE TITLE
Reverse of T and F

### ISSUE THREAD

**Issue by kaiyuhou** [mvcisback/py-aiger-bdd#10]
Hello - 

We discover another potential issue:

When we choose an expression expr = ~x & y & z & w (It would be FALSE if x is 1, or any of y, z, or w is 0.), we get 
![image](https://user-images.githubusercontent.com/11606036/134746946-77e19318-308e-4bd1-87ba-8b5d6beca74c.png)
which says it would be TRUE if x is 1, or any of y, z, or w is 0. We have compared the corresponding json file, and it is the same as the png file:

```
{
"level_of_var": {"x": 0, "z": 1, "y": 2, "w": 3},
"roots": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
"2": [0, "F", "T"],
"3": [1, "F", "T"],
"4": [2, "F", "T"],
"5": [3, "F", "T"],
"6": [0, -4, "T"],
"7": [1, "F", 4],
"8": [0, -7, "T"],
"9": [2, "F", 5],
"10": [1, "F", 9],
"11": [0, -10, "T"]
}

```

So we suspect the bdd itself has T and F reversed, or is the whole expression reversed?

-------

We are attempting to use your tool to parse a bdd generated by JavaBDD (it looks like a ZDD), and then translate it to aiger. In this process, we encounter another issue: your parser does not allow an F to appear on a low branch, for example, "7": [1, 4, "F"]. Otherwise, it has an assertion error:

```
Traceback (most recent call last):
  File "/home/kaiyu/Workspace/py-aiger-bdd/main.py", line 51, in <module>
    json_to_png_max_as_root('old3.json', 'old3.png')
  File "/home/kaiyu/Workspace/py-aiger-bdd/main.py", line 21, in json_to_png_max_as_root
    manager.load(json_file)
  File "/home/kaiyu/Workspace/py-aiger-bdd/venv/lib/python3.6/site-packages/dd/autoref.py", line 237, in load
    return _copy.load_json(filename, self)
  File "/home/kaiyu/Workspace/py-aiger-bdd/venv/lib/python3.6/site-packages/dd/_copy.py", line 205, in load_json
    nodes = _load_json(f, bdd, load_order, cache)
  File "/home/kaiyu/Workspace/py-aiger-bdd/venv/lib/python3.6/site-packages/dd/_copy.py", line 217, in _load_json
    _store_line(d, bdd, context, cache)
  File "/home/kaiyu/Workspace/py-aiger-bdd/venv/lib/python3.6/site-packages/dd/_copy.py", line 257, in _store_line
    _make_node(d, bdd, context, cache)
  File "/home/kaiyu/Workspace/py-aiger-bdd/venv/lib/python3.6/site-packages/dd/_copy.py", line 278, in _make_node
    assert not u.negated
AssertionError
```
Is there a way to bypass this assertion and parse a random BDD? Or is there another tool to translate a BDD to aiger? Thank you very much.

**Comment by mvcisback** [comment]
The assertion is from the underlying bdd library (the python package dd).

Regarding the switching of F and T, I'd double check that the relevant edges aren't negated.

`dd` uses CUDD which represents Boolean functions as edge complemented reduced ordered BDDs

**Comment by mvcisback** [comment]
@kaiyuhou is this also due to dumping all nodes?

**Comment by kaiyuhou** [comment]
I don't think so. I think some json files cannot be parsed, if for some node the low branch is an 'F'. Maybe it is due the assumption of ROBDD as you said.

**Comment by mvcisback** [comment]
I see. I will close this issue then as it's not a problem with aiger-bdd
